USE hoa_yeu_thuong_db;
GO

DECLARE @name VARCHAR(128)
DECLARE cur CURSOR LOCAL FOR
SELECT name FROM sys.objects WHERE type = 'P'
OPEN cur
FETCH NEXT FROM cur INTO @name
WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC ('DROP PROCEDURE ' + @name)
    FETCH NEXT FROM cur INTO @name
END
CLOSE cur
DEALLOCATE cur
GO
